name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    #if: github.event.base_ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Publish to GitHub Packages
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew -Pversion=${GITHUB_REF:11} -Pgpr.user= -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish
      - name: Generate API documentation
        run: ./gradlew -Pversion=${GITHUB_REF:11} dokkaHtmlMultiModule
      - name: Publish API documentation
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          folder: build/dokka/htmlMultiModule
          clean: true
          branch: gh-pages
          target-folder: apidoc
