name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew -Pversion=${GITHUB_REF:11} -Pgpr.user= -Pgpr.key=${{ secrets.GITHUB_TOKEN }} build publish

      - name: Generate API documentation
        run: ./gradlew dokkaHtmlMultiModule
      - name: Publish API documentation
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: build/dokka/htmlMultiModule
          TARGET_FOLDER: apidoc
