name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build sourceJar dokkaJar
      - name: Publish to Maven Central
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.CENTRAL_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.CENTRAL_PASSWD }}
        run: ./gradlew -Pversion=${GITHUB_REF:11} publish closeAndReleaseStagingRepository
      - name: Generate API documentation
        run: ./gradlew -Pversion=${GITHUB_REF:11} dokkaHtmlMultiModule
      - name: Publish API documentation
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: build/dokka/htmlMultiModule
          clean: true
          branch: gh-pages
          target-folder: apidoc
