name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew build
      - name: Publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
      - name: Publish to GitHub Packages
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew -Pversion=${GITHUB_REF:11} -Pgpr.user= -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish
      - name: Generate API documentation
        run: ./gradlew -Pversion=${GITHUB_REF:11} dokkaHtmlMultiModule
      - name: Publish API documentation
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          folder: build/dokka/htmlMultiModule
          clean: true
          branch: gh-pages
          target-folder: apidoc
